import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google"

const europa = localFont({
  src: [
    {
      path: "./fonts/EuropaNuovaBold.ttf",
      weight: "700"
    },
    {
      path: "./fonts/EuropaNuovaExtraBold.ttf",
      weight: "800"
    },
    {
      path: "./fonts/EuropaNuovaRegular.ttf",
      weight: "400"
    }
  ],
  variable: "--font-europa"
})
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${europa.variable} ${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
